# Generated by Django 4.0.6 on 2022-07-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicetype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('services', models.CharField(max_length=100)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('servicetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.servicetype', verbose_name='Service Type')),
            ],
        ),
    ]
