# Generated by Django 4.0.6 on 2022-07-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='user_id',
        ),
    ]
