# Generated by Django 4.0.6 on 2022-07-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_admin_customer_staff_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admin_Profile',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customer_Profile',
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Staff_Profile',
        ),
    ]
