# Generated by Django 4.0.6 on 2022-07-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_servicetype_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_price',
            new_name='serviceprice',
        ),
    ]
