# Generated by Django 4.0.6 on 2022-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_customer_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gendertype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stafftype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
