# Generated by Django 4.0.6 on 2022-07-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_admin_admin_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Profile',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='Admin_Profile',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Staff_Profile',
            new_name='Staff',
        ),
    ]
