# Generated by Django 4.0.6 on 2022-07-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_user_admin_user_id_rename_user_staff_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='gendertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stafftype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
