# Generated by Django 4.0.6 on 2022-07-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_user_id_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='stafftype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.stafftype', verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='gendertype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stafftype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
