# Generated by Django 4.0.6 on 2022-07-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_customuser_user_name_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gendertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.gender', verbose_name='Gender'),
        ),
    ]
