# Generated by Django 4.0.6 on 2022-07-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_admin_stafftype_alter_gendertype_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user',
            new_name='admin',
        ),
    ]
