# Generated by Django 4.0.6 on 2022-07-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_user_admin_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='staff',
        ),
    ]
