# Generated by Django 4.0.6 on 2022-07-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_gender_admin_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stafftype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stafftype', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='gender',
            new_name='gendertype',
        ),
        migrations.AddField(
            model_name='admin',
            name='stafftype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.stafftype', verbose_name='Stafftype'),
        ),
    ]
