# Generated by Django 4.0.6 on 2022-07-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customertype_customer_gendertype_staff_gendertype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Gendertype',
        ),
    ]
