# Generated by Django 4.0.5 on 2022-07-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=50, null=True, verbose_name='First Name')),
                ('customer_lname', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('services', models.CharField(max_length=50, null=True, verbose_name='Services')),
                ('appointmentStatus', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Successful', 'Successful')], default='Pending', max_length=20, verbose_name='Appointment Statis')),
                ('apptDate', models.DateTimeField(blank=True, null=True)),
                ('appt_timeEnd', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
