# Generated by Django 4.0.6 on 2022-07-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=50, null=True, verbose_name='First Name')),
                ('customer_lname', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('services', models.JSONField(default=dict)),
                ('firstStylist', models.CharField(max_length=30, null=True, verbose_name='First Stylist')),
                ('secondStylist', models.CharField(max_length=30, null=True, verbose_name='Second Stylist')),
                ('appointmentStatus', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Successful', 'Successful'), ('Approved', 'Approved')], default='Pending', max_length=20, verbose_name='Appointment Status')),
                ('apptDate', models.DateField(blank=True, null=True, verbose_name='Appointment Date')),
                ('appt_timeStart', models.TimeField(blank=True, null=True, verbose_name='Time Start')),
            ],
        ),
    ]
