# Generated by Django 4.0.5 on 2022-07-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointmentStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Successful', 'Successful')], default='Pending', max_length=20, verbose_name='Appointment Status'),
        ),
    ]
