# Generated by Django 4.0.6 on 2022-07-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_num',
            field=models.CharField(max_length=11, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Email Address'),
        ),
    ]
