# Generated by Django 4.0.6 on 2022-07-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_appointment_contact_num_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apptType',
            field=models.CharField(choices=[('Online', 'Online'), ('Walk In', 'Walk In')], default='Online', max_length=20, verbose_name='Appointment Type'),
        ),
    ]
