# Generated by Django 4.0.6 on 2022-07-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('system', '0003_appointment_appttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, to='account.services', verbose_name='Service'),
        ),
    ]
