# Generated by Django 4.0.5 on 2022-07-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_appointments_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='services',
            field=models.JSONField(default=dict),
        ),
    ]
