# Generated by Django 4.0.5 on 2022-07-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_appointments_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appt_timeEnd',
            new_name='appt_timeStart',
        ),
    ]
