# Generated by Django 4.0.6 on 2022-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_appointment_services_appointment_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.JSONField(default=dict),
        ),
    ]
