# Generated by Django 4.0.5 on 2022-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_rename_appt_timeend_appointments_appt_timestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='apptDate',
            field=models.DateField(blank=True, null=True, verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appt_timeStart',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Start'),
        ),
    ]
