# Generated by Django 4.0.6 on 2022-07-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('system', '0005_remove_appointment_services_appointment_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer_fname',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer_lname',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='Customer'),
        ),
    ]
