# Generated by Django 4.0.5 on 2022-07-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_appointments_apptdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='firstStylist',
            field=models.CharField(max_length=30, null=True, verbose_name='First Stylist'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='secondStylist',
            field=models.CharField(max_length=30, null=True, verbose_name='Second Stylist'),
        ),
    ]
