# Generated by Django 4.0.5 on 2022-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_rename_appointments_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Successful', 'Successful'), ('Approved', 'Approved')], default='Pending', max_length=20, verbose_name='Appointment Status'),
        ),
    ]
