# Generated by Django 4.0.6 on 2022-07-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_appointment_contact_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Address'),
        ),
    ]
