# Generated by Django 4.0.6 on 2022-07-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_remove_joborderform_insproductused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborderform',
            name='consumed',
        ),
        migrations.AddField(
            model_name='joborderform',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
