# Generated by Django 4.0.6 on 2022-07-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_remove_joborderform_consumed_joborderform_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborderform',
            name='date_today',
        ),
        migrations.RemoveField(
            model_name='joborderform',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='joborderform',
            name='servicePrices',
        ),
        migrations.AlterField(
            model_name='joborderform',
            name='appointmentInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.appointment'),
        ),
    ]
