# Generated by Django 4.0.6 on 2022-07-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_remove_joborderform_date_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderform',
            name='servicePrices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
