# Generated by Django 4.0.6 on 2022-07-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_joborderform_stylist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joborderform',
            old_name='stylist',
            new_name='finalStylist',
        ),
    ]
