# Generated by Django 4.0.6 on 2022-07-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_rename_stylist_joborderform_finalstylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Confirmed', 'Confirmed'), ('Successful', 'Successful')], default='Pending', max_length=20, verbose_name='Appointment Status'),
        ),
        migrations.AlterField(
            model_name='joborderform',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Total'),
        ),
    ]
