# Generated by Django 4.0.6 on 2022-07-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_alter_appointment_appointmentstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100, null=True, verbose_name='Review')),
                ('isPositive', models.BooleanField(null=True)),
                ('isNegative', models.BooleanField(null=True)),
                ('feedbackInfo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='system.joborderform', verbose_name='Form')),
            ],
        ),
    ]
