# Generated by Django 4.0.6 on 2022-07-26 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_clientfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='feedbackInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='system.joborderform', verbose_name='joborderform'),
        ),
    ]
