# Generated by Django 4.0.6 on 2022-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_alter_clientfeedback_feedbackinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Confirmed', 'Confirmed'), ('Ongoing', 'Ongoing'), ('Successful', 'Successful')], default='Pending', max_length=20, verbose_name='Appointment Status'),
        ),
    ]
