# Generated by Django 4.0.6 on 2022-08-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_alter_appointment_appointmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='adminReply',
            field=models.CharField(max_length=100, null=True, verbose_name='Admin Reply'),
        ),
    ]
