# Generated by Django 4.0.6 on 2022-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_clientfeedback_adminreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='adminReply',
            field=models.TextField(max_length=300, null=True, verbose_name='Admin Reply'),
        ),
    ]
