# Generated by Django 4.0.6 on 2022-08-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_profile_pic'),
        ('system', '0025_alter_clientfeedback_adminreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderform',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='serviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalStylist', models.CharField(max_length=200, null=True, verbose_name='Stylist')),
                ('serviceType', models.CharField(max_length=200, null=True, verbose_name='Service Type')),
                ('dateDone', models.DateTimeField(auto_now=True, null=True)),
                ('customerName', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer', verbose_name='Customer Name')),
                ('serviceName', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.services', verbose_name='Service Name')),
            ],
        ),
    ]
