# Generated by Django 4.0.6 on 2022-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_joborderform_timestamp_servicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='serviceName',
            field=models.CharField(max_length=200, null=True, verbose_name='Service Name'),
        ),
    ]
