# Generated by Django 4.0.6 on 2022-07-24 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('pickupstat_id', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Transaction Successful', 'Transaction Successful'), ('Confirmed', 'Confirmed')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdType_Name', models.CharField(max_length=200, unique=True, verbose_name='Product Type')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Price')),
                ('product_pickupID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='otcProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('Prod_Desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('Prod_stockQty', models.IntegerField(verbose_name='Stock Quantity')),
                ('Prod_Price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('Prod_Image', models.ImageField(default='placeholder-image.png', null=True, upload_to='product_images', verbose_name='Product Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('digital', models.BooleanField(default=False, null=True)),
                ('Cat_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category', verbose_name='Category')),
                ('ProdType_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.producttype', verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Over-the-Counter Product',
            },
        ),
        migrations.CreateModel(
            name='OrderPickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.DateField(null=True, verbose_name='Pickup Date')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.otcproduct')),
            ],
        ),
        migrations.CreateModel(
            name='insProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('Prod_Desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('Prod_stockQty', models.IntegerField(verbose_name='Stock Quantity')),
                ('Prod_Price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('Prod_Image', models.ImageField(default='placeholder-image.png', null=True, upload_to='product_images', verbose_name='Product Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('Cat_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category', verbose_name='Category')),
                ('ProdType_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.producttype', verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'In-salon Product',
            },
        ),
    ]
