# Generated by Django 4.0.6 on 2022-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insproduct',
            name='totalUsed',
            field=models.IntegerField(default=0, verbose_name='Total Times Used'),
        ),
    ]
