# Generated by Django 4.0.6 on 2022-07-28 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_insproduct_totalused'),
    ]

    operations = [
        migrations.AddField(
            model_name='insproduct',
            name='add_stock',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='insproduct',
            name='deduct_stock',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='insproduct',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='insproduct',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otcproduct',
            name='add_stock',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='otcproduct',
            name='deduct_stock',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='otcproduct',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='otcproduct',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='otcStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Name', models.CharField(max_length=200, null=True, verbose_name='Product Name')),
                ('Prod_Desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('Prod_stockQty', models.IntegerField(null=True, verbose_name='Stock Quantity')),
                ('Prod_Price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Price')),
                ('Prod_Image', models.ImageField(default='placeholder-image.png', null=True, upload_to='product_images', verbose_name='Product Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('add_stock', models.IntegerField(blank=True, default='0', null=True)),
                ('deduct_stock', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('Cat_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category', verbose_name='Category')),
                ('ProdType_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.producttype', verbose_name='Product Type')),
            ],
        ),
        migrations.CreateModel(
            name='insStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Name', models.CharField(max_length=200, null=True, verbose_name='Product Name')),
                ('Prod_Desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('Prod_stockQty', models.IntegerField(null=True, verbose_name='Stock Quantity')),
                ('Prod_Price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Price')),
                ('Prod_Image', models.ImageField(default='placeholder-image.png', null=True, upload_to='product_images', verbose_name='Product Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('add_stock', models.IntegerField(blank=True, default='0', null=True)),
                ('deduct_stock', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('Cat_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category', verbose_name='Category')),
                ('ProdType_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.producttype', verbose_name='Product Type')),
            ],
        ),
    ]
