# Generated by Django 4.0.6 on 2022-08-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_insproduct_add_stock_insproduct_deduct_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Measurement_Type', models.CharField(max_length=200, unique=True, verbose_name='Product Measurement')),
            ],
        ),
        migrations.AddField(
            model_name='otcproduct',
            name='Measurement_Num',
            field=models.IntegerField(null=True, verbose_name='Measurement Number'),
        ),
        migrations.AddField(
            model_name='otcproduct',
            name='Measurement_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.measurementtype', verbose_name='Measurement Type'),
        ),
    ]
